# Test `lung_fractals` library 
- All angles in `deg`.
- `x, y, z` are rounded to closest integer.

In [1]:
from tlib.lung import *

Using TensorFlow backend.



***
### Test `Cursor` class moving system

Position cursor on z axis facing down

In [2]:
cr = Cursor(cursor_position=(0, 0, 20), azimuth=90, altitude=180, plane_versor=(1,0,0))
cr

Position: x: 0 y: 0 z: 20
Facing angles:  azimuth: 90 altitude: 180
Facing versor: (0.0, 0.0, -1.0)
Lying plane versor :(1, 0, 0)

Turn facing direction right by 90 deg so that now is facing parallel to y

In [3]:
cr.turn(90)
cr

Position: x: 0 y: 0 z: 20
Facing angles:  azimuth: 90.0 altitude: 90.0
Facing versor: (0.0, 1.0, 0.0)
Lying plane versor :(1, 0, 0)

Move cursor forward by 30 along y axis

In [5]:
cr.move_forward(30)
cr

Position: x: 0 y: 30 z: 20
Facing angles:  azimuth: 90.0 altitude: 90.0
Facing versor: (0.0, 1.0, 0.0)
Lying plane versor :(1, 0, 0)

Rotate lying plane so that now is `(y, x)` plane

In [6]:
cr.rotate_plane(90)
cr

Position: x: 0 y: 30 z: 20
Facing angles:  azimuth: 90.0 altitude: 90.0
Facing versor: (0.0, 1.0, 0.0)
Lying plane versor :(0.0, 0.0, -1.0)

Turn left by 90 so that cursor faces -x axis

In [7]:
cr.turn(-90)
cr

Position: x: 0 y: 30 z: 20
Facing angles:  azimuth: 180.0 altitude: 90.0
Facing versor: (-1.0, 0.0, 0.0)
Lying plane versor :(0.0, 0.0, -1.0)

In [2]:
# c = Cursor(x=0, y=0, z=0, altitude=90, azimuth=90)

# c.get_cartesian_coordinates()



#         # add node to skeleton and update skeleton position
#         self.current_skeleton_node = SkeletonNode(*end_coord, parent_node=self.current_skeleton_node)
#         # draw the line on canvas, default thickness value is 0 pixels
#         self.volume.draw_line(start_coord, end_coord, thickness_radius)


***
## Other tests
### Test `Direction` class moving features

In [1]:
from tlib.lung import *

Using TensorFlow backend.


Position cursor on z axis facing down

In [2]:
pt = Direction(x=0, y=0, z=20, azimuth=90, altitude=180)
pt

Position: x: 0 y: 0 z: 20
Facing angles:  azimuth: 90 altitude: 180
Facing versor: (0.0, 0.0, -1.0)
Lying plane versor :(1, 0, 0)

Turn facing direction right by 90 deg so that now is facing parallel to y

In [3]:
pt.turn(90)
pt

Position: x: 0 y: 0 z: 20
Facing angles:  azimuth: 90.0 altitude: 90.0
Facing versor: (0.0, 1.0, 0.0)
Lying plane versor :(1, 0, 0)

Move cursor forward by 30 along y axis

In [4]:
pt.move_forward(30)
pt

Position: x: 0 y: 30 z: 20
Facing angles:  azimuth: 90.0 altitude: 90.0
Facing versor: (0.0, 1.0, 0.0)
Lying plane versor :(1, 0, 0)

Rotate lying plane so that now is `(y, x)` plane

In [5]:
pt.rotate_plane(90)
pt

Position: x: 0 y: 30 z: 20
Facing angles:  azimuth: 90.0 altitude: 90.0
Facing versor: (0.0, 1.0, 0.0)
Lying plane versor :(0.0, 0.0, -1.0)

Turn left by 90 so that cursor faces -x axis

In [6]:
pt.turn(-90)
pt

Position: x: 0 y: 30 z: 20
Facing angles:  azimuth: 180.0 altitude: 90.0
Facing versor: (-1.0, 0.0, 0.0)
Lying plane versor :(0.0, 0.0, -1.0)

#### Test `move_forward`

In [2]:
pt = Direction(x=0, y=0, z=20, azimuth=90, altitude=180)

In [3]:
pt.get_direction()

{'altitude': 180, 'azimuth': 90}

In [4]:
pt.plane_versor

(1, 0, 0)

In [5]:
pt.turn(90)

In [6]:
pt.get_direction()

{'altitude': 0, 'azimuth': 0}

In [ ]:
pt.facing_versor

In [4]:
pt.move_forward(10)

In [5]:
pt.get_cartesian_coordinates()

{'x': 0, 'y': 0, 'z': 10}

In [6]:
pt.reverse_direction()

In [7]:
pt.move_forward(10)

In [8]:
pt.get_cartesian_coordinates()

{'x': 0, 'y': 0, 'z': 20}

In [10]:
pt.get_direction()

{'altitude': 0.0, 'azimuth': 270.0}

In [10]:
pt.get_direction()

{'altitude': 0.0, 'azimuth': 270.0}

In [11]:
pt.turn(45)

In [12]:
pt.get_direction()

{'altitude': 58.31007906582538, 'azimuth': 270.0}

In [15]:
pt.get_direction()

{'altitude': 0, 'azimuth': 0}

In [14]:
pt.get_polar_coordinates()

{'r': 17.320508075688775, 'theta': 54.735610317245346, 'phi': 45.0}

#### Test `reverse_direction`

In [2]:
d = Direction(x=0, y=0, z=0, azimuth=0, altitude=0)

DEBUG:root:Point defined using cartesian coordinates.


In [3]:
d.get_direction(), d.reverse_direction(), d.get_direction()

DEBUG:root:phi: 0.0, theta: 0.0
DEBUG:root:reverse_direction x -0.0 y -0.0 z -1.0
DEBUG:root:radius after reverse_direction 1.0.


({'altitude': 0, 'azimuth': 0}, None, {'altitude': 180.0, 'azimuth': 180.0})

In [4]:
d = Direction(x=0, y=0, z=0, azimuth=0, altitude=90)
d.reverse_direction()
d.get_direction()

DEBUG:root:Point defined using cartesian coordinates.
DEBUG:root:phi: 0.0, theta: 1.5707963267948966
DEBUG:root:reverse_direction x -1.0 y -0.0 z -6.123233995736766e-17
DEBUG:root:radius after reverse_direction 1.0.


{'altitude': 90.0, 'azimuth': 180.0}

In [5]:
d = Direction(x=0, y=0, z=0, azimuth=45, altitude=45)
d.reverse_direction()
d.get_direction()

DEBUG:root:Point defined using cartesian coordinates.
DEBUG:root:phi: 0.7853981633974483, theta: 0.7853981633974483
DEBUG:root:reverse_direction x -0.5 y -0.4999999999999999 z -0.7071067811865476
DEBUG:root:radius after reverse_direction 1.0.


{'altitude': 135.0, 'azimuth': 225.0}

In [7]:
d.rotate_direction(new_altitude=10)
d.get_direction()

{'altitude': 10, 'azimuth': 225.0}

In [8]:
d.rotate_direction(new_altitude=0, new_azimuth=90)
d.reverse_direction()
d.get_direction()

DEBUG:root:phi: 1.5707963267948966, theta: 0.0
DEBUG:root:reverse_direction x -0.0 y -0.0 z -1.0
DEBUG:root:radius after reverse_direction 1.0.


{'altitude': 180.0, 'azimuth': 180.0}

In [9]:
d.rotate_direction(new_altitude=90, new_azimuth=90)
d.reverse_direction()
d.get_direction()

DEBUG:root:phi: 1.5707963267948966, theta: 1.5707963267948966
DEBUG:root:reverse_direction x -6.123233995736766e-17 y -1.0 z -6.123233995736766e-17
DEBUG:root:radius after reverse_direction 1.0.


{'altitude': 90.0, 'azimuth': 270.0}

In [10]:
d.rotate_direction(new_altitude=90, new_azimuth=90)
d.reverse_direction()
d.get_direction()

DEBUG:root:phi: 1.5707963267948966, theta: 1.5707963267948966
DEBUG:root:reverse_direction x -6.123233995736766e-17 y -1.0 z -6.123233995736766e-17
DEBUG:root:radius after reverse_direction 1.0.


{'altitude': 90.0, 'azimuth': 270.0}

***
### Test `Point` class.

### Test `from_polar_to_cartesian`.

If `r=0` then it's the origin

In [11]:
Point.from_polar_to_cartesian(r=0, phi=0, theta=0)

DEBUG:root:phi: 0.0, theta: 0.0


{'x': 0, 'y': 0, 'z': 0}

In [12]:
Point.from_polar_to_cartesian(r=0, phi=200, theta=-1010)

DEBUG:root:phi: 3.490658503988659, theta: 1.2217304763960306


{'x': 0, 'y': 0, 'z': 0}

If `phi = 90, 270`, point lies in `(y, z)` plane.

In [13]:
Point.from_polar_to_cartesian(r=10, phi=90, theta=45)

DEBUG:root:phi: 1.5707963267948966, theta: 0.7853981633974483


{'x': 0, 'y': 7, 'z': 7}

In [14]:
Point.from_polar_to_cartesian(r=10, phi=270, theta=45)

DEBUG:root:phi: 4.71238898038469, theta: 0.7853981633974483


{'x': 0, 'y': -7, 'z': 7}

If `phi = 180`, point lies in `(x, z)` plane with negative `x`.

In [15]:
Point.from_polar_to_cartesian(r=10, phi=180, theta=45)

DEBUG:root:phi: 3.141592653589793, theta: 0.7853981633974483


{'x': -7, 'y': 0, 'z': 7}

In [17]:
Point.from_polar_to_cartesian(r=10, phi=180, theta=180+45)

ERROR:root:theta must be in between 0 and 180.


ValueError: 

Careful that rounding to integer can lead to wierd results:

In [18]:
Point.from_polar_to_cartesian(r=1, phi=45, theta=45)

DEBUG:root:phi: 0.7853981633974483, theta: 0.7853981633974483


{'x': 0, 'y': 0, 'z': 1}

### Test `from_cartesian_to_polar`.

Check origin goes into origin.

In [19]:
Point.from_cartesian_to_polar(x=0, y=0, z=0)

{'r': 0, 'theta': 0, 'phi': 0}

Check: `theta=90` when `z=0`.

In [20]:
Point.from_cartesian_to_polar(x=10, y=20, z=0)

{'r': 22.360679774997898, 'theta': 90.0, 'phi': 63.43494882292201}

In [21]:
Point.from_cartesian_to_polar(x=-10, y=-200, z=0)

{'r': 200.24984394500785, 'theta': 90.0, 'phi': 267.1375947738883}

In [22]:
Point.from_cartesian_to_polar(x=-10, y=0, z=0)

{'r': 10.0, 'theta': 90.0, 'phi': 180.0}

In [23]:
Point.from_cartesian_to_polar(x=10, y=0, z=10)

{'r': 14.142135623730951, 'theta': 45.00000000000001, 'phi': 0.0}

In [24]:
Point.from_cartesian_to_polar(x=10, y=0, z=-10)

{'r': 14.142135623730951, 'theta': 135.0, 'phi': 0.0}

Test all the cases with negative axes

In [25]:
Point.from_cartesian_to_polar(x=1, y=1, z=0)

{'r': 1.4142135623730951, 'theta': 90.0, 'phi': 45.0}

In [29]:
Point.from_cartesian_to_polar(x=-1, y=-0.001, z=0)

{'r': 1.000000499999875, 'theta': 90.0, 'phi': 180.0572957604145}

Test `Point` constructor

if `r=0` is origin

In [17]:
pt = Point(x=0, y=0, z=0)
pt.get_cartesian_coordinates(), pt.get_polar_coordinates()

({'x': 0, 'y': 0, 'z': 0}, {'r': 0, 'theta': 0, 'phi': 0})

In [18]:
pt = Point(r=0, phi=100, theta=0)
pt.get_cartesian_coordinates(), pt.get_polar_coordinates()

({'x': 0, 'y': 0, 'z': 0}, {'r': 0, 'theta': 0, 'phi': 0})

When `theta=0` then `x=y=0` (and `phi` doesn't matter)

In [27]:
pt = Point(r=10, phi=45, theta=0)
pt.get_cartesian_coordinates(), pt.get_polar_coordinates()

({'x': 0, 'y': 0, 'z': 10}, {'r': 10.0, 'theta': 0.0, 'phi': 90.0})

In [28]:
pt = Point(x=0, y=0, z=10)
pt.get_cartesian_coordinates(), pt.get_polar_coordinates()

({'x': 0, 'y': 0, 'z': 10}, {'r': 10.0, 'theta': 0.0, 'phi': 90.0})

When `Point` is defined with polar coordinates the radius is automatically adjusted so that the corresponding Cartesian coordinates are integer

In [8]:
pt = Point(r=10, phi=45, theta=90)
pt.get_cartesian_coordinates(), pt.get_polar_coordinates()

({'x': 7, 'y': 7, 'z': 0},
 {'r': 9.899494936611665, 'theta': 90.0, 'phi': 45.0})

When `theta=180`, `z` is negative (and `phi` doesn't matter).

In [9]:
pt = Point(r=10, phi=45, theta=180)
pt.get_cartesian_coordinates(), pt.get_polar_coordinates()

({'x': 0, 'y': 0, 'z': -10}, {'r': 10.0, 'theta': 180.0, 'phi': 90.0})

In [10]:
pt = Point(r=10, phi=45, theta=180)
pt.get_cartesian_coordinates(), pt.get_polar_coordinates()

({'x': 0, 'y': 0, 'z': -10}, {'r': 10.0, 'theta': 180.0, 'phi': 90.0})